default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tsubuyakishiro-_development

test:
  <<: *default
  database: tsubuyakishiro-_test

production:
  <<: *default
  database: tsubuyakishiro-_production
  username: tsubuyakishiro-
  password: <%= ENV['TSUBUYAKISHIRO-_DATABASE_PASSWORD'] %>
